-- Initial administrator. Replace password_hash with a hash generated by the SIF backend before production.
-- This placeholder is intentionally not a usable password.
INSERT INTO users (id, username, password_hash, role, active)
VALUES (1, 'admin', 'REPLACE_WITH_SIF_PASSWORD_HASH', 'Administrator', 1);
